/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as MiprojetRouteImport } from './routes/miprojet'
import { Route as MembreRouteImport } from './routes/membre'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembreIndexRouteImport } from './routes/membre/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifierMatriculeRouteImport } from './routes/verifier.$matricule'
import { Route as MiprojetUtilisateursRouteImport } from './routes/miprojet.utilisateurs'
import { Route as MembreProfilRouteImport } from './routes/membre/profil'
import { Route as MembrePrestationsRouteImport } from './routes/membre/prestations'
import { Route as MembreFicheRouteImport } from './routes/membre/fiche'
import { Route as MembreDocumentsRouteImport } from './routes/membre/documents'
import { Route as MembreCotisationsRouteImport } from './routes/membre/cotisations'
import { Route as MembreCarteRouteImport } from './routes/membre/carte'
import { Route as AdminPrestationsRouteImport } from './routes/admin/prestations'
import { Route as AdminOpportunitesRouteImport } from './routes/admin/opportunites'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMiprojetRouteImport } from './routes/admin/miprojet'
import { Route as AdminMembresRouteImport } from './routes/admin/membres'
import { Route as AdminDroitsAdhesionRouteImport } from './routes/admin/droits-adhesion'
import { Route as AdminCotisationsRouteImport } from './routes/admin/cotisations'
import { Route as AdminActualitesRouteImport } from './routes/admin/actualites'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const MiprojetRoute = MiprojetRouteImport.update({
  id: '/miprojet',
  path: '/miprojet',
  getParentRoute: () => rootRouteImport,
} as any)
const MembreRoute = MembreRouteImport.update({
  id: '/membre',
  path: '/membre',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembreIndexRoute = MembreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifierMatriculeRoute = VerifierMatriculeRouteImport.update({
  id: '/verifier/$matricule',
  path: '/verifier/$matricule',
  getParentRoute: () => rootRouteImport,
} as any)
const MiprojetUtilisateursRoute = MiprojetUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => MiprojetRoute,
} as any)
const MembreProfilRoute = MembreProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => MembreRoute,
} as any)
const MembrePrestationsRoute = MembrePrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => MembreRoute,
} as any)
const MembreFicheRoute = MembreFicheRouteImport.update({
  id: '/fiche',
  path: '/fiche',
  getParentRoute: () => MembreRoute,
} as any)
const MembreDocumentsRoute = MembreDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MembreRoute,
} as any)
const MembreCotisationsRoute = MembreCotisationsRouteImport.update({
  id: '/cotisations',
  path: '/cotisations',
  getParentRoute: () => MembreRoute,
} as any)
const MembreCarteRoute = MembreCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => MembreRoute,
} as any)
const AdminPrestationsRoute = AdminPrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitesRoute = AdminOpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMiprojetRoute = AdminMiprojetRouteImport.update({
  id: '/miprojet',
  path: '/miprojet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembresRoute = AdminMembresRouteImport.update({
  id: '/membres',
  path: '/membres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDroitsAdhesionRoute = AdminDroitsAdhesionRouteImport.update({
  id: '/droits-adhesion',
  path: '/droits-adhesion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotisationsRoute = AdminCotisationsRouteImport.update({
  id: '/cotisations',
  path: '/cotisations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActualitesRoute = AdminActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/membre': typeof MembreRouteWithChildren
  '/miprojet': typeof MiprojetRouteWithChildren
  '/opportunites': typeof OpportunitesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/droits-adhesion': typeof AdminDroitsAdhesionRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/miprojet': typeof AdminMiprojetRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunites': typeof AdminOpportunitesRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/membre/carte': typeof MembreCarteRoute
  '/membre/cotisations': typeof MembreCotisationsRoute
  '/membre/documents': typeof MembreDocumentsRoute
  '/membre/fiche': typeof MembreFicheRoute
  '/membre/prestations': typeof MembrePrestationsRoute
  '/membre/profil': typeof MembreProfilRoute
  '/miprojet/utilisateurs': typeof MiprojetUtilisateursRoute
  '/verifier/$matricule': typeof VerifierMatriculeRoute
  '/admin/': typeof AdminIndexRoute
  '/membre/': typeof MembreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/miprojet': typeof MiprojetRouteWithChildren
  '/opportunites': typeof OpportunitesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/droits-adhesion': typeof AdminDroitsAdhesionRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/miprojet': typeof AdminMiprojetRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunites': typeof AdminOpportunitesRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/membre/carte': typeof MembreCarteRoute
  '/membre/cotisations': typeof MembreCotisationsRoute
  '/membre/documents': typeof MembreDocumentsRoute
  '/membre/fiche': typeof MembreFicheRoute
  '/membre/prestations': typeof MembrePrestationsRoute
  '/membre/profil': typeof MembreProfilRoute
  '/miprojet/utilisateurs': typeof MiprojetUtilisateursRoute
  '/verifier/$matricule': typeof VerifierMatriculeRoute
  '/admin': typeof AdminIndexRoute
  '/membre': typeof MembreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/membre': typeof MembreRouteWithChildren
  '/miprojet': typeof MiprojetRouteWithChildren
  '/opportunites': typeof OpportunitesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/droits-adhesion': typeof AdminDroitsAdhesionRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/miprojet': typeof AdminMiprojetRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunites': typeof AdminOpportunitesRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/membre/carte': typeof MembreCarteRoute
  '/membre/cotisations': typeof MembreCotisationsRoute
  '/membre/documents': typeof MembreDocumentsRoute
  '/membre/fiche': typeof MembreFicheRoute
  '/membre/prestations': typeof MembrePrestationsRoute
  '/membre/profil': typeof MembreProfilRoute
  '/miprojet/utilisateurs': typeof MiprojetUtilisateursRoute
  '/verifier/$matricule': typeof VerifierMatriculeRoute
  '/admin/': typeof AdminIndexRoute
  '/membre/': typeof MembreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/forum'
    | '/inscription'
    | '/login'
    | '/membre'
    | '/miprojet'
    | '/opportunites'
    | '/reset-password'
    | '/scanner'
    | '/sitemap.xml'
    | '/admin/actualites'
    | '/admin/cotisations'
    | '/admin/droits-adhesion'
    | '/admin/membres'
    | '/admin/miprojet'
    | '/admin/notifications'
    | '/admin/opportunites'
    | '/admin/prestations'
    | '/membre/carte'
    | '/membre/cotisations'
    | '/membre/documents'
    | '/membre/fiche'
    | '/membre/prestations'
    | '/membre/profil'
    | '/miprojet/utilisateurs'
    | '/verifier/$matricule'
    | '/admin/'
    | '/membre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/contact'
    | '/faq'
    | '/forum'
    | '/inscription'
    | '/login'
    | '/miprojet'
    | '/opportunites'
    | '/reset-password'
    | '/scanner'
    | '/sitemap.xml'
    | '/admin/actualites'
    | '/admin/cotisations'
    | '/admin/droits-adhesion'
    | '/admin/membres'
    | '/admin/miprojet'
    | '/admin/notifications'
    | '/admin/opportunites'
    | '/admin/prestations'
    | '/membre/carte'
    | '/membre/cotisations'
    | '/membre/documents'
    | '/membre/fiche'
    | '/membre/prestations'
    | '/membre/profil'
    | '/miprojet/utilisateurs'
    | '/verifier/$matricule'
    | '/admin'
    | '/membre'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/forum'
    | '/inscription'
    | '/login'
    | '/membre'
    | '/miprojet'
    | '/opportunites'
    | '/reset-password'
    | '/scanner'
    | '/sitemap.xml'
    | '/admin/actualites'
    | '/admin/cotisations'
    | '/admin/droits-adhesion'
    | '/admin/membres'
    | '/admin/miprojet'
    | '/admin/notifications'
    | '/admin/opportunites'
    | '/admin/prestations'
    | '/membre/carte'
    | '/membre/cotisations'
    | '/membre/documents'
    | '/membre/fiche'
    | '/membre/prestations'
    | '/membre/profil'
    | '/miprojet/utilisateurs'
    | '/verifier/$matricule'
    | '/admin/'
    | '/membre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForumRoute: typeof ForumRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  MembreRoute: typeof MembreRouteWithChildren
  MiprojetRoute: typeof MiprojetRouteWithChildren
  OpportunitesRoute: typeof OpportunitesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScannerRoute: typeof ScannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifierMatriculeRoute: typeof VerifierMatriculeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miprojet': {
      id: '/miprojet'
      path: '/miprojet'
      fullPath: '/miprojet'
      preLoaderRoute: typeof MiprojetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membre': {
      id: '/membre'
      path: '/membre'
      fullPath: '/membre'
      preLoaderRoute: typeof MembreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membre/': {
      id: '/membre/'
      path: '/'
      fullPath: '/membre/'
      preLoaderRoute: typeof MembreIndexRouteImport
      parentRoute: typeof MembreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verifier/$matricule': {
      id: '/verifier/$matricule'
      path: '/verifier/$matricule'
      fullPath: '/verifier/$matricule'
      preLoaderRoute: typeof VerifierMatriculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miprojet/utilisateurs': {
      id: '/miprojet/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/miprojet/utilisateurs'
      preLoaderRoute: typeof MiprojetUtilisateursRouteImport
      parentRoute: typeof MiprojetRoute
    }
    '/membre/profil': {
      id: '/membre/profil'
      path: '/profil'
      fullPath: '/membre/profil'
      preLoaderRoute: typeof MembreProfilRouteImport
      parentRoute: typeof MembreRoute
    }
    '/membre/prestations': {
      id: '/membre/prestations'
      path: '/prestations'
      fullPath: '/membre/prestations'
      preLoaderRoute: typeof MembrePrestationsRouteImport
      parentRoute: typeof MembreRoute
    }
    '/membre/fiche': {
      id: '/membre/fiche'
      path: '/fiche'
      fullPath: '/membre/fiche'
      preLoaderRoute: typeof MembreFicheRouteImport
      parentRoute: typeof MembreRoute
    }
    '/membre/documents': {
      id: '/membre/documents'
      path: '/documents'
      fullPath: '/membre/documents'
      preLoaderRoute: typeof MembreDocumentsRouteImport
      parentRoute: typeof MembreRoute
    }
    '/membre/cotisations': {
      id: '/membre/cotisations'
      path: '/cotisations'
      fullPath: '/membre/cotisations'
      preLoaderRoute: typeof MembreCotisationsRouteImport
      parentRoute: typeof MembreRoute
    }
    '/membre/carte': {
      id: '/membre/carte'
      path: '/carte'
      fullPath: '/membre/carte'
      preLoaderRoute: typeof MembreCarteRouteImport
      parentRoute: typeof MembreRoute
    }
    '/admin/prestations': {
      id: '/admin/prestations'
      path: '/prestations'
      fullPath: '/admin/prestations'
      preLoaderRoute: typeof AdminPrestationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunites': {
      id: '/admin/opportunites'
      path: '/opportunites'
      fullPath: '/admin/opportunites'
      preLoaderRoute: typeof AdminOpportunitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/miprojet': {
      id: '/admin/miprojet'
      path: '/miprojet'
      fullPath: '/admin/miprojet'
      preLoaderRoute: typeof AdminMiprojetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/membres': {
      id: '/admin/membres'
      path: '/membres'
      fullPath: '/admin/membres'
      preLoaderRoute: typeof AdminMembresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/droits-adhesion': {
      id: '/admin/droits-adhesion'
      path: '/droits-adhesion'
      fullPath: '/admin/droits-adhesion'
      preLoaderRoute: typeof AdminDroitsAdhesionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cotisations': {
      id: '/admin/cotisations'
      path: '/cotisations'
      fullPath: '/admin/cotisations'
      preLoaderRoute: typeof AdminCotisationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actualites': {
      id: '/admin/actualites'
      path: '/actualites'
      fullPath: '/admin/actualites'
      preLoaderRoute: typeof AdminActualitesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActualitesRoute: typeof AdminActualitesRoute
  AdminCotisationsRoute: typeof AdminCotisationsRoute
  AdminDroitsAdhesionRoute: typeof AdminDroitsAdhesionRoute
  AdminMembresRoute: typeof AdminMembresRoute
  AdminMiprojetRoute: typeof AdminMiprojetRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOpportunitesRoute: typeof AdminOpportunitesRoute
  AdminPrestationsRoute: typeof AdminPrestationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActualitesRoute: AdminActualitesRoute,
  AdminCotisationsRoute: AdminCotisationsRoute,
  AdminDroitsAdhesionRoute: AdminDroitsAdhesionRoute,
  AdminMembresRoute: AdminMembresRoute,
  AdminMiprojetRoute: AdminMiprojetRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOpportunitesRoute: AdminOpportunitesRoute,
  AdminPrestationsRoute: AdminPrestationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MembreRouteChildren {
  MembreCarteRoute: typeof MembreCarteRoute
  MembreCotisationsRoute: typeof MembreCotisationsRoute
  MembreDocumentsRoute: typeof MembreDocumentsRoute
  MembreFicheRoute: typeof MembreFicheRoute
  MembrePrestationsRoute: typeof MembrePrestationsRoute
  MembreProfilRoute: typeof MembreProfilRoute
  MembreIndexRoute: typeof MembreIndexRoute
}

const MembreRouteChildren: MembreRouteChildren = {
  MembreCarteRoute: MembreCarteRoute,
  MembreCotisationsRoute: MembreCotisationsRoute,
  MembreDocumentsRoute: MembreDocumentsRoute,
  MembreFicheRoute: MembreFicheRoute,
  MembrePrestationsRoute: MembrePrestationsRoute,
  MembreProfilRoute: MembreProfilRoute,
  MembreIndexRoute: MembreIndexRoute,
}

const MembreRouteWithChildren =
  MembreRoute._addFileChildren(MembreRouteChildren)

interface MiprojetRouteChildren {
  MiprojetUtilisateursRoute: typeof MiprojetUtilisateursRoute
}

const MiprojetRouteChildren: MiprojetRouteChildren = {
  MiprojetUtilisateursRoute: MiprojetUtilisateursRoute,
}

const MiprojetRouteWithChildren = MiprojetRoute._addFileChildren(
  MiprojetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForumRoute: ForumRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  MembreRoute: MembreRouteWithChildren,
  MiprojetRoute: MiprojetRouteWithChildren,
  OpportunitesRoute: OpportunitesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScannerRoute: ScannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifierMatriculeRoute: VerifierMatriculeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
